version: "3.9"
services:
  diplicity-map-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diplicity-map-application
    entrypoint: ["npm", "run", "dev"]
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - diplicity-net
    env_file:
      - .env
    ports:
      - "3000:3000"
networks:
  diplicity-net:
    name: diplicity-net
    driver: bridge
